use std::collections::BTreeMap;

use crate::normalization::unicode::casefold_text;

/// Auditable high-frequency UTS #39-style confusables. NFKC is applied before
/// this table so compatibility forms (full-width and mathematical alphabets)
/// are handled by Unicode data rather than a second hand-maintained table.
/// A complete UTS #39 data pack can be layered on without changing this API.
pub fn confusable_map() -> BTreeMap<char, char> {
    [
        ('а', 'a'),
        ('е', 'e'),
        ('о', 'o'),
        ('р', 'p'),
        ('с', 'c'),
        ('у', 'y'),
        ('х', 'x'),
        ('і', 'i'),
        ('ј', 'j'),
        ('ѕ', 's'),
        ('һ', 'h'),
        ('ԁ', 'd'),
        ('ԃ', 'd'),
        ('ԍ', 'n'),
        ('ԛ', 'q'),
        ('ԝ', 'w'),
        ('ԟ', 'p'),
        ('ԡ', 'l'),
        ('ԣ', 'h'),
        ('ԧ', 'h'),
        ('ԩ', 'h'),
        ('ԫ', 'h'),
        ('ԭ', 'o'),
        ('ԯ', 't'),
        ('ґ', 'r'),
        ('қ', 'q'),
        ('ң', 'n'),
        ('ғ', 'f'),
        ('ҷ', 'j'),
        ('ү', 'y'),
        ('ұ', 'y'),
        ('ҳ', 'h'),
        ('ӯ', 'y'),
        ('ӏ', 'l'),
        ('Α', 'A'),
        ('Β', 'B'),
        ('Ε', 'E'),
        ('Ζ', 'Z'),
        ('Η', 'H'),
        ('Ι', 'I'),
        ('Κ', 'K'),
        ('Μ', 'M'),
        ('Ν', 'N'),
        ('Ο', 'O'),
        ('Ρ', 'P'),
        ('Τ', 'T'),
        ('Υ', 'Y'),
        ('Χ', 'X'),
        ('α', 'a'),
        ('ν', 'v'),
        ('τ', 't'),
        ('υ', 'u'),
        ('ϲ', 'c'),
        ('ϳ', 'j'),
        ('ϵ', 'e'),
        ('ϱ', 'p'),
        ('ϰ', 'k'),
        ('ϴ', 'O'),
        ('Ϲ', 'C'),
        ('Ϻ', 'M'),
        ('ϻ', 'm'),
        ('Ͻ', 'C'),
        ('Ͽ', 'C'),
        ('Ⅰ', 'I'),
        ('А', 'A'),
        ('В', 'B'),
        ('Е', 'E'),
        ('К', 'K'),
        ('М', 'M'),
        ('Н', 'H'),
        ('О', 'O'),
        ('Р', 'P'),
        ('С', 'C'),
        ('Т', 'T'),
        ('Х', 'X'),
        ('Ѐ', 'E'),
        ('Ѕ', 'S'),
        ('І', 'I'),
        ('Ј', 'J'),
        ('Љ', 'L'),
        ('Њ', 'N'),
        ('Ќ', 'K'),
        ('Ў', 'Y'),
        ('Џ', 'D'),
        ('ѓ', 'r'),
        ('ѕ', 's'),
        ('і', 'i'),
        ('ј', 'j'),
        ('љ', 'l'),
        ('њ', 'n'),
        ('ќ', 'k'),
        ('ў', 'y'),
        ('џ', 'd'),
        ('０', '0'),
        ('１', '1'),
        ('２', '2'),
        ('３', '3'),
        ('４', '4'),
        ('５', '5'),
        ('６', '6'),
        ('７', '7'),
        ('８', '8'),
        ('９', '9'),
        ('ａ', 'a'),
        ('ｐ', 'p'),
        ('ｙ', 'y'),
        ('ｌ', 'l'),
    ]
    .into_iter()
    .collect()
}

pub fn skeleton(text: &str) -> String {
    let map = confusable_map();
    casefold_text(text)
        .chars()
        .map(|ch| map.get(&ch).copied().unwrap_or(ch))
        .collect()
}
